// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/service/auth-service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_service_auth_service_proto protoreflect.FileDescriptor

const file_api_service_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/service/auth-service.proto\x12\x04auth\x1a\x1aapi/service/messages.proto2\xf4\x01\n" +
	"\vAuthService\x128\n" +
	"\rValidateToken\x12\x12.auth.TokenRequest\x1a\x13.auth.TokenResponse\x129\n" +
	"\bRegister\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12>\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x13.auth.LoginResponseB\x8f\x01\n" +
	"\bcom.authB\x10AuthServiceProtoP\x01ZAgithub.com/Zholdaskali/go-microservices/protobuf/api/service/auth\xa2\x02\x03AXX\xaa\x02\x04Auth\xca\x02\x04Auth\xe2\x02\x10Auth\\GPBMetadata\xea\x02\x04Authb\x06proto3"

var file_api_service_auth_service_proto_goTypes = []any{
	(*TokenRequest)(nil),        // 0: auth.TokenRequest
	(*RegisterRequest)(nil),     // 1: auth.RegisterRequest
	(*LoginRequest)(nil),        // 2: auth.LoginRequest
	(*RefreshTokenRequest)(nil), // 3: auth.RefreshTokenRequest
	(*TokenResponse)(nil),       // 4: auth.TokenResponse
	(*RegisterResponse)(nil),    // 5: auth.RegisterResponse
	(*LoginResponse)(nil),       // 6: auth.LoginResponse
}
var file_api_service_auth_service_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.ValidateToken:input_type -> auth.TokenRequest
	1, // 1: auth.AuthService.Register:input_type -> auth.RegisterRequest
	2, // 2: auth.AuthService.Login:input_type -> auth.LoginRequest
	3, // 3: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	4, // 4: auth.AuthService.ValidateToken:output_type -> auth.TokenResponse
	5, // 5: auth.AuthService.Register:output_type -> auth.RegisterResponse
	6, // 6: auth.AuthService.Login:output_type -> auth.LoginResponse
	6, // 7: auth.AuthService.RefreshToken:output_type -> auth.LoginResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_service_auth_service_proto_init() }
func file_api_service_auth_service_proto_init() {
	if File_api_service_auth_service_proto != nil {
		return
	}
	file_api_service_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_auth_service_proto_rawDesc), len(file_api_service_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_auth_service_proto_goTypes,
		DependencyIndexes: file_api_service_auth_service_proto_depIdxs,
	}.Build()
	File_api_service_auth_service_proto = out.File
	file_api_service_auth_service_proto_goTypes = nil
	file_api_service_auth_service_proto_depIdxs = nil
}
